image: ubuntu

version: '{build}'

install:
- docker pull docker.io/geek1011/nickeltc:1.0
- docker pull golang:1.13-buster

build_script:
- sh: cd kobo-dotfile-hack   && docker run --rm --volume="$PWD:/src" --workdir=/src --entrypoint=make docker.io/geek1011/nickeltc:1.0 && cd ..
- sh: cd dictword-test       && docker run --rm --volume="$PWD:/src" --workdir=/src --entrypoint=make docker.io/geek1011/nickeltc:1.0 && cd ..
- sh: cd dictbug-trace       && docker run --rm --volume="$PWD:/src" --workdir=/src --entrypoint=make docker.io/geek1011/nickeltc:1.0 && cd ..
- sh: cd kobopatch-livepatch && make DOCKER=docker all kplive-cross                                                                   && cd ..

test: off

artifacts:
- path: kobo-dotfile-hack/KoboRoot.tgz
- path: dictword-test/dictword-test.so
- path: dictword-test/dwt-wrap
- path: dictbug-trace/libdictbug-trace.so
- path: kobopatch-livepatch/kplived
- path: kobopatch-livepatch/kplive-windows.exe
- path: kobopatch-livepatch/kplive-linux-64bit
- path: kobopatch-livepatch/kplive-darwin-64bit
