kind: pipeline
name: kobo-dotfile-hack
type: docker

steps:
- name: submodules
  image: docker.io/geek1011/nickeltc:1.0
  when:
    event: [push, pull_request, tag]
  command: ["git", "submodule", "update", "--init", "--recursive"]
- name: build-native
  image: gcc:latest
  commands:
  - cd ./kobo-dotfile-hack
  - mkdir -p ./tmp/.kobo ./tmp/.test ./tmp/.adobe-digital-editions ./tmp/.adds
  - HOME=./tmp make -f Makefile.native test
  depends_on: [submodules]
- name: build-kobo
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./kobo-dotfile-hack
  - make
  depends_on: [submodules]

trigger:
  event:
    exclude: [promote]

---

kind: pipeline
name: kobo-dotfile-hack-ng
type: docker

steps:
- name: submodules
  image: docker.io/geek1011/nickeltc:1.0
  when:
    event: [push, pull_request, tag]
  command: ["git", "submodule", "update", "--init", "--recursive"]
- name: build
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./kobo-dotfile-hack-ng
  - make all koboroot

trigger:
  event:
    exclude: [promote]

---

kind: pipeline
name: NickelSeries
type: docker

steps:
- name: submodules
  image: docker.io/geek1011/nickeltc:1.0
  when:
    event: [push, pull_request, tag]
  command: ["git", "submodule", "update", "--init", "--recursive"]
- name: build
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./NickelSeries
  - make all koboroot

trigger:
  event:
    exclude: [promote]

---

kind: pipeline
name: dictword-test
type: docker

steps:
- name: submodules
  image: docker.io/geek1011/nickeltc:1.0
  when:
    event: [push, pull_request, tag]
  command: ["git", "submodule", "update", "--init", "--recursive"]
- name: build
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./dictword-test
  - make

trigger:
  event:
    exclude: [promote]

---

kind: pipeline
name: dictbug-trace
type: docker

steps:
- name: submodules
  image: docker.io/geek1011/nickeltc:1.0
  when:
    event: [push, pull_request, tag]
  command: ["git", "submodule", "update", "--init", "--recursive"]
- name: build
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./dictbug-trace
  - make

trigger:
  event:
    exclude: [promote]
