kind: pipeline
name: kobo-dotfile-hack
type: docker

steps:
- name: build-native
  image: gcc:latest
  commands:
  - cd ./kobo-dotfile-hack
  - mkdir -p ./tmp/.kobo ./tmp/.test ./tmp/.adobe-digital-editions ./tmp/.adds
  - HOME=./tmp make -f Makefile.native test
  depends_on: [clone]
- name: build-kobo
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./kobo-dotfile-hack
  - make
  depends_on: [clone]
- name: upload
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./kobo-dotfile-hack
  - curl -F'file=@KoboRoot.tgz' https://0x0.st
  depends_on: [build-kobo]

trigger:
  event:
    exclude: [promote]

---

kind: pipeline
name: NickelSeries
type: docker

steps:
- name: build
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./NickelSeries
  - make all koboroot
- name: upload
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./NickelSeries
  - curl -F'file=@KoboRoot.tgz' https://0x0.st

trigger:
  event:
    exclude: [promote]

---

kind: pipeline
name: dictword-test
type: docker

steps:
- name: build
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./dictword-test
  - make
- name: upload
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./dictword-test
  - curl -F'file=@dictword-test.so' https://0x0.st

trigger:
  event:
    exclude: [promote]

---

kind: pipeline
name: dictbug-trace
type: docker

steps:
- name: build
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./dictbug-trace
  - make
- name: upload
  image: docker.io/geek1011/nickeltc:1.0
  commands:
  - cd ./dictbug-trace
  - curl -F'file=@libdictbug-trace.so' https://0x0.st

trigger:
  event:
    exclude: [promote]

---

kind: pipeline
name: kobopatch-livepatch
type: docker

steps:
- name: build
  image: golang:1.13-buster
  commands:
  - cd ./kobopatch-livepatch
  - make DOCKER=
- name: upload
  image: debian:9
  commands:
  - cd ./kobopatch-livepatch
  - apt -qq update >/dev/null && apt -qq install -y curl >/dev/null
  - curl -F'file=@kplive' https://0x0.st
  - curl -F'file=@kplived' https://0x0.st

trigger:
  event:
    exclude: [promote]