image: ubuntu

version: '{build}'

install:
- git submodule update --init --recursive
- docker pull ghcr.io/pgaskin/nickeltc:1.0

build_script:
- sh: docker run --rm --volume="$APPVEYOR_BUILD_FOLDER:/src" --workdir="/src/kobo-dotfile-hack"    --entrypoint=make ghcr.io/pgaskin/nickeltc:1.0
- sh: docker run --rm --volume="$APPVEYOR_BUILD_FOLDER:/src" --workdir="/src/kobo-dotfile-hack-ng" --entrypoint=make ghcr.io/pgaskin/nickeltc:1.0 all koboroot
- sh: docker run --rm --volume="$APPVEYOR_BUILD_FOLDER:/src" --workdir="/src/NickelSeries"         --entrypoint=make ghcr.io/pgaskin/nickeltc:1.0 all koboroot
- sh: docker run --rm --volume="$APPVEYOR_BUILD_FOLDER:/src" --workdir="/src/dictword-test"        --entrypoint=make ghcr.io/pgaskin/nickeltc:1.0
- sh: docker run --rm --volume="$APPVEYOR_BUILD_FOLDER:/src" --workdir="/src/dictbug-trace"        --entrypoint=make ghcr.io/pgaskin/nickeltc:1.0

test: off

artifacts:
- path: kobo-dotfile-hack/KoboRoot.tgz
- path: kobo-dotfile-hack-ng/libdfh.so
- path: kobo-dotfile-hack-ng/KoboRoot.tgz
- path: NickelSeries/libns.so
- path: NickelSeries/KoboRoot.tgz
- path: dictword-test/dictword-test.so
- path: dictword-test/dwt-wrap
- path: dictbug-trace/libdictbug-trace.so
